config/routes.rb
Rails.application.routes.draw do
  root 'series#index'

  get 'series/index'
  post 'series/search'
  get 'series/search'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  require 'will_paginate/array'

  def index
    @response = ThetvdbClient.token
  end

  def search
    @search_param = params[:series_name]
    @results = ThetvdbClient.search(@search_param).paginate(:page => params[:page], :per_page => 10)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "BBSeries", '', class: "navbar-brand", id: "logo" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <div class="col-md-6 col-md-offset-2">
        <form class="" action="<%= series_search_path %>" method="post" style="margin-top:8px">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <div class="input-group">
              <input type="text" class="form-control" placeholder="Find New Series" name="series_name" id="series_name">
              <div class="input-group-btn">
                  <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
              </div>
          </div>
        </form>
      </div>

      <!--
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    -->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Log in", '' %></li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bbseries</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>

</body>
</html>

app/views/series/index.html.erb
<!--
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <form >
    <div class="input-group">
        <input type="text" class="form-control" placeholder="Find New Series" name="srch-term" id="srch-term">
        <div class="input-group-btn">
            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
        </div>
    </div>
    </form>
  </div>
</div>
-->
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>Current Series</h1>
    <p>Find me in app/views/series/index.html.erb</p>
    <p><%= @response %></p>
  </div>
</div>

app/views/series/search.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>Search Results</h1>
  </div>
</div>

<%= will_paginate @results %>

<div class="row">
  <div class="panel panel-default">
    <div class="panel-heading">Panel heading</div>
    <div class="panel-body">
      <p>Segue os resultados para a busca por <b><%= @search_param %></b></p>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>First Aired</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @results.each do |series| %>
        <tr>
          <th scope="row"><%= series.id %></th>
          <td><%= series.name %></td>
          <td><%= series.first_aired %></td>
          <td><%= series.status %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>